

I2C_BASEADDR    = 1
PUMPS_NUM        = 1
PUMPS_NUMHATS        = 1

PUMP_CONFIG[] = ?

PUMP_CONFIG[1].HAT       = 0
PUMP_CONFIG[1].FLOW_RATE     = 150
PUMP_CONFIG[1].MLPS          = 10
PUMP_CONFIG[1].ACCEL         = 100



